// flow-typed signature: 838c105e6badcb035840a7704916af89
// flow-typed version: <<STUB>>/@types/google-apps-script_v^0.0.27/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/google-apps-script'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/google-apps-script' {
  declare module.exports: GoogleAppsScript;
}
